baseURL = 'http://example.org/hci'
languageCode = 'en-us'
title = 'Human Computer Interaction'
theme = "blank"
uglyurls = true

[menu]

[[menu.main]]
  name = 'Home'
  identifier = 'home'
  url = '/'
  weight = -10

[[menu.main]]
  name = 'Schedule'
  identifier = 'schedule'
  url = '/schedule.html'
  weight = 10

[[menu.main]]
  name = 'First MC test'
  identifier = 'first_mc_test'
  url = '/practicals/mc1-slots.html'
  parent = "schedule"
  weight = 10

[[menu.main]]
  name = 'Second MC test'
  identifier = 'second_mc_test'
  url = '/practicals/mc2-slots.html'
  parent = "schedule"
  weight = 20

[[menu.main]]
  name = 'Grading review'
  identifier = 'grading_review'
  url = '/practicals/grading-review.html'
  parent = "schedule"
  weight = 30

[[menu.main]]
  name = 'Exercises'
  identifier = 'exercises'
  url = '/practicals/'
  weight = 20

[[menu.main]]
  name = 'Exercise 1'
  identifier = 'exercise_1'
  url = '/practicals/exer1.html'
  parent = "exercises"
  weight = 10

[[menu.main]]
  name = 'Exercise 2'
  identifier = 'exercise_2'
  url = '/practicals/exer2.html'
  parent = "exercises"
  weight = 20

[[menu.main]]
  name = 'Exercise 3'
  identifier = 'exercise_3'
  url = '/practicals/exer3.html'
  parent = "exercises"
  weight = 30

[[menu.main]]
  name = 'Exercise 4'
  identifier = 'exercise_4'
  url = '/practicals/mctest.html'
  parent = "exercises"
  weight = 40

[[menu.main]]
  name = 'Materials'
  identifier = 'materials'
  url = '/practicals/materials/'
  weight = 30

[[menu.main]]
  name = 'Guides'
  identifier = 'guides'
  url = '/practicals/'
  weight = 40

[[menu.main]]
  name = 'Using Webex'
  identifier = 'using_webex'
  url = '/guide-using-webex.html'
  parent = "guides"
  weight = 10

[[menu.main]]
  name = 'Using Sapphire'
  identifier = 'using_sapphire'
  url = '/practicals/guide-using-sapphire.html'
  parent = "guides"
  weight = 20

[[menu.main]]
  name = 'Session Capture'
  identifier = 'session_capture'
  url = '/practicals/guide-session-capture.html'
  parent = "guides"
  weight = 30

[[menu.main]]
  name = 'Video Editing'
  identifier = 'video_editing'
  url = '/practicals/guide-video-editing.html'
  parent = "guides"
  weight = 40

[[menu.main]]
  name = 'Video Transcoding'
  identifier = 'video_transcoding'
  url = '/practicals/guide-video-transcoding.html'
  parent = "guides"
  weight = 50

[[menu.main]]
  name = 'Validating HTML'
  identifier = 'validating_html'
  url = '/practicals/validation'
  parent = "guides"
  weight = 60

[[menu.main]]
  name = 'Previous Reports'
  identifier = 'previous_reports'
  url = '/reports/'
  weight = 50

[[menu.main]]
  name = 'Tutors'
  identifier = 'tutors'
  url = '/practicals/tutors'
  weight = 60

