baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Human Computer Interaction'
theme = "blank"

[menu]

[[menu.main]]
  name = 'Schedule'
  identifier = 'schedule'
  url = '/schedule/'

[[menu.main]]
  name = 'Test Slots'
  identifier = 'test_slots'
  url = '/schedule/test_slots/'
  parent = "schedule"

[[menu.main]]
  name = 'Grading review'
  identifier = 'grading_review'
  url = '/schedule/grading_review/'
  parent = "schedule"

[[menu.main]]
  name = 'Exercises'
  identifier = 'exercises'
  url = '/exercises/'

[[menu.main]]
  name = 'Exercise 1'
  identifier = 'exercise_1'
  url = '/exercises/exercise_1/'
  parent = "exercises"

[[menu.main]]
  name = 'Exercise 2'
  identifier = 'exercise_2'
  url = '/exercises/exercise_2/'
  parent = "exercises"

[[menu.main]]
  name = 'Exercise 3'
  identifier = 'exercise_3'
  url = '/exercises/exercise_3/'
  parent = "exercises"

[[menu.main]]
  name = 'MC Test'
  identifier = 'mc_test'
  url = '/exercises/mc_test/'
  parent = "exercises"

[[menu.main]]
  name = 'Materials'
  identifier = 'materials'
  url = '/materials/'

[[menu.main]]
  name = 'Heuristic Evaluation Plan'
  identifier = 'heuristic_evaluation_plan'
  url = '/materials/heuristic_evaluation_plan/'
  parent = "materials"

[[menu.main]]
  name = 'Heuristic Evaluation Report'
  identifier = 'heuristic_evaluation_report'
  url = '/materials/heuristic_evaluation_report/'
  parent = "materials"

[[menu.main]]
  name = 'Guides'
  identifier = 'guides'
  url = '/guides/'

[[menu.main]]
  name = 'Using Webex'
  identifier = 'using_webex'
  url = '/guides/using_webex/'
  parent = "guides"

[[menu.main]]
  name = 'Using Sapphire'
  identifier = 'using_sapphire'
  url = '/guides/using_sapphire/'
  parent = "guides"

[[menu.main]]
  name = 'Session Capture'
  identifier = 'session_capture'
  url = '/guides/session_capture/'
  parent = "guides"

[[menu.main]]
  name = 'Video Editing'
  identifier = 'video_editing'
  url = '/guides/video_editing/'
  parent = "guides"

[[menu.main]]
  name = 'Video Transcoding'
  identifier = 'video_transcoding'
  url = '/guides/video_transcoding/'
  parent = "guides"

[[menu.main]]
  name = 'Validating HTML'
  identifier = 'validating_html'
  url = '/guides/validating_html/'
  parent = "guides"

[[menu.main]]
  name = 'Example Reports'
  identifier = 'example_reports'
  url = '/example_reports/'

